name: Deploy site

on:
  push:
    branches: [ main ]

jobs:
  doc-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Mkdocs
        run: mkdocs build --verbose --clean --strict

      - name: Post-Mkdocs touch/copy files
        run: |
          touch site/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: site
          clean: true
